# Generated by Django 5.0.4 on 2024-05-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_automate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automate',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
