# Generated by Django 5.0.4 on 2024-05-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_automate_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='automate',
            name='rules',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
